algoritmo "semnome"
// Função :
// Autor : David
// Data : 21/06/2022
// Seção de Declarações 
var
a,b: caracter
motorista, cart: logico

inicio
//entrada
escreval("Digite sua idade:")
leia(a)

escreval("Digite se tem ou não tem carteira de motorista:")
leia(b)

//processamento
motorista <- (a>=18)
cart <-(b= "sim") ou (b= "nao")



//Saída
escreval("Sua idade?",motorista)
escreval("Tem carteira de motorista?",cart)



fimalgoritmo
